
CONNECTION_ROLE_CLIENT = "client"
CONNECTION_ROLE_SERVER = "server"

DISCOVERY_METHOD_BROKER = "broker"
DISCOVERY_METHOD_MULTICAST = "multicast"
DISCOVERY_METHOD_STATIC = "static"

DISCOVERY_STATUS_FOUND = "device_discovered"
DISCOVERY_STATUS_LOST = "device_lost"

DISCOVERY_ROLE_CALLER = "caller"
DISCOVERY_ROLE_RESPONDER = "responder"

