# rotation
CLOCKWISE = "CLOCKWISE"
COUNTERCLOCKWISE = "COUNTERCLOCKWISE"
POSITIVE = "POSITIVE"
NEGATIVE = "NEGATIVE"

# cartesian
UP = "UP"
DOWN = "DOWN"
LEFT = "LEFT"
RIGHT = "RIGHT"
FORWARD = "FORWARD"
BACKWARD = "BACKWARD"

# relative
SHORTEST_PATH = "SHORTEST_PATH"
LONGEST_PATH = "LONGEST_PATH"
TOP = "TOP"
BOTTOM = "BOTTOM"

# process directions
START = "START"
END = "END"
SUCCESS = "SUCCESS"
FAILURE = "FAILURE"
ERROR = "ERROR"
EXCEPTION = "EXCEPTION"
